### ISSUE TITLE
base address

### ISSUE THREAD

**Issue by Exotikcheatt** [imp1338/Fortnite-External#1]
i have no base address when i map wrong driver ? +star

**Comment by imp1338** [comment]
Please Update Your Open Device, I Have Set It Wrong Sorry For The Misinformation

\\\\.\\\\{019237847183893-187826146798791-8167357189463-8722534623721}

**Comment by imp1338** [comment]
Your issue has been fixed, please replace the memorys.hh file with the one that was just updated, it should fix your issues, sorry for the inconvenience. - _Imp_
